#!/bin/bash

function print_help_and_exit
{
cat >&2 << 'EOF'

'ftdmp-dock' produces many dimeric structures by docking two monomeric structures

Options:
    --monomer1 | -m1          string  *  monomer 1 input file path
    --monomer2 | -m2          string  *  monomer 2 input file path
    --job-name                string     job name to use as prefix for identifiers
    --logs-output             string     logs output directory path
    --parallel-parts          number     total number of parallel parts, default is 1
    --ftdock-keep             number     ftdock keep parameter, default is 1
    --ftdock-angle-step       number     ftdock angle step parameter, default is 9
    --help | -h                          flag to display help message and exit

Standard output:
    space-separated table of docking results
    
Examples:

    ftdmp-dock -m1 monomer1.pdb -m2 monomer2.pdb --logs-output docking_results --parallel-parts 16

EOF
exit 1
}

readonly ZEROARG=$0
ALLARGS=("$@")

if [ -z "$1" ]
then
	print_help_and_exit
fi

if [[ $ZEROARG == *"/"* ]]
then
	cd $(dirname $ZEROARG)
	FTDMPDIR="$(pwd)"
	export PATH="${FTDMPDIR}:${PATH}"
	if [ -d "${FTDMPDIR}/core/3D_Dock/progs" ]
	then
		export PATH="${FTDMPDIR}/core/3D_Dock/progs:${PATH}"
	fi
	cd - &> /dev/null
fi

command -v voronota-js &> /dev/null || { echo >&2 "Error: 'voronota-js' executable not in binaries path"; exit 1; }
command -v ftdmp-prepare-monomer &> /dev/null || { echo >&2 "Error: 'ftdmp-prepare-monomer' executable not in binaries path"; exit 1; }
command -v ftdock &> /dev/null || { echo >&2 "Error: 'ftdock' executable not in binaries path"; exit 1; }

MONOMERFILE1=""
MONOMERFILE2=""
JOBNAME=""
OUTDIR=""
PARALLEL_PARTS="1"
PARALLEL_ID=""
FTDOCK_KEEP="1"
FTDOCK_ANGLE_STEP="9"
HELP_MODE="false"

while [[ $# > 0 ]]
do
	OPTION="$1"
	OPTARG="$2"
	shift
	case $OPTION in
	-m1|--monomer1)
		MONOMERFILE1="$OPTARG"
		shift
		;;
	-m2|--monomer2)
		MONOMERFILE2="$OPTARG"
		shift
		;;
	--job-name)
		JOBNAME="$OPTARG"
		shift
		;;
	--logs-output)
		OUTDIR="$OPTARG"
		shift
		;;
	--parallel-parts)
		PARALLEL_PARTS="$OPTARG"
		shift
		;;
	--parallel-id)
		PARALLEL_ID="$OPTARG"
		shift
		;;
	--ftdock-keep)
		FTDOCK_KEEP="$OPTARG"
		shift
		;;
	--ftdock-angle-step)
		FTDOCK_ANGLE_STEP="$OPTARG"
		shift
		;;
	-h|--help)
		HELP_MODE="true"
		;;
	*)
		echo >&2 "Error: invalid command line option '$OPTION'"
		exit 1
		;;
	esac
done

if [ "$HELP_MODE" == "true" ]
then
	print_help_and_exit
fi

if [ -z "$MONOMERFILE1" ]
then
	echo >&2 "Error: no static input file specified"
	exit 1
fi

if [ ! -s "$MONOMERFILE1" ]
then
	echo >&2 "Error: no static input file '$MONOMERFILE1'"
	exit 1
fi

if [ -z "$MONOMERFILE2" ]
then
	echo >&2 "Error: no static input file specified"
	exit 1
fi

if [ ! -s "$MONOMERFILE2" ]
then
	echo >&2 "Error: no mobile input file '$MONOMERFILE2'"
	exit 1
fi

if [ -z "$PARALLEL_PARTS" ] || [ "$PARALLEL_PARTS" -ne "$PARALLEL_PARTS" ] || [ "$PARALLEL_PARTS" -lt "1" ]
then
	echo >&2 "Error: invalid number of parallel parts '$PARALLEL_PARTS', must be a positive number"
	exit 1
fi

if [ -n "$PARALLEL_ID" ]
then
	if [ "$PARALLEL_ID" -ne "$PARALLEL_ID" ] || [ "$PARALLEL_ID" -lt "1" ] || [ "$PARALLEL_ID" -gt "$PARALLEL_PARTS" ]
	then
		echo >&2 "Error: invalid parallel part ID '$PARALLEL_ID', must be a positive number less than the total number of parts ($PARALLEL_PARTS)"
		exit 1
	fi
fi

if [ -z "$OUTDIR" ]
then
	readonly TMPLDIR=$(mktemp -d)
	trap "rm -r $TMPLDIR" EXIT
	
	OUTDIR="${TMPLDIR}/docking"
fi

if [ -z "$PARALLEL_ID" ]
then
	seq 1 "$PARALLEL_PARTS" | xargs -L 1 -P "$PARALLEL_PARTS" "$ZEROARG" "${ALLARGS[@]}" --logs-output "$OUTDIR" --parallel-id
	
	{
	find "$OUTDIR" -type f -name 'part_results_table.txt' | xargs -L 1 -P 1 head -n 1 | sort | uniq | awk '{print "ID " $0}'
	find "$OUTDIR" -type f -name 'part_results_table.txt' | xargs -L 1 -P 1 tail -n +2 | sort -n -k 1 | tac | awk -v jobname="$JOBNAME" '{print jobname NR " " $0}'
	} \
	> "${OUTDIR}/all_parts_results_table.txt"
	
	cat "${OUTDIR}/all_parts_results_table.txt"
	
	exit 0
fi

OUTDIR="${OUTDIR}/part${PARALLEL_ID}"
mkdir -p "$OUTDIR"

ftdmp-prepare-monomer --input "$MONOMERFILE1" --output-for-ftdock "$OUTDIR/monomer1.pdb"

if [ ! -s "$OUTDIR/monomer1.pdb" ]
then
	echo >&2 "Error: failed to prepare monomer 1"
	exit 1
fi

ftdmp-prepare-monomer --input "$MONOMERFILE2" --output-for-ftdock "$OUTDIR/monomer2.pdb"

if [ ! -s "$OUTDIR/monomer2.pdb" ]
then
	echo >&2 "Error: failed to prepare monomer 2"
	exit 1
fi

cd "$OUTDIR"

ftdock -static monomer1.pdb -mobile monomer2.pdb -noelec -keep "$FTDOCK_KEEP" -angle_step "$FTDOCK_ANGLE_STEP" -parallel_parts "$PARALLEL_PARTS" -parallel_id "$PARALLEL_ID" > log_ftdock.txt

if [ ! -s "ftdock_global.dat" ]
then
	echo >&2 "Error: failed to run ftdock"
	exit 1
fi

FTDOCK_GRID_SIZE="$(cat ftdock_global.dat | egrep '^Global grid size ' | awk '{print $5}')"

FTDOCK_TOTAL_SPAN="$(cat ftdock_global.dat | egrep '^Global total span ' | awk '{print $6}')"

if [ -z "$FTDOCK_GRID_SIZE" ] || [ -z "$FTDOCK_TOTAL_SPAN" ] || [ "$FTDOCK_GRID_SIZE" -ne "$FTDOCK_GRID_SIZE" ]
then
	echo >&2 "Error: failed to read ftdock grid parameters"
	exit 1
fi

{
echo "scscore scale x y z a1 a2 a3"

cat ftdock_global.dat | egrep '^G_DATA' \
| awk -v gridsize="$FTDOCK_GRID_SIZE" -v totalspan="$FTDOCK_TOTAL_SPAN" '{print $4 " " (totalspan/gridsize) " " $6 " " $7 " " $8 " " $9 " " $10 " " $11}'
} \
> "part_results_table.txt"

rm "monomer1.pdb" "monomer2.pdb"

