#!/bin/bash

function print_help_and_exit
{
cat >&2 << 'EOF'

'ftdmp-score' evaluates docking results produced by 'ftdmp-dock'

Options:
    --input                   string  *  input file path
    --monomers-prefix         string     monomer files prefix, default is ''
    --parallel-parts          number     total number of parallel parts, default is 1
    --voronota-js-path        string     voronota-js executables path, default is ''
    --help | -h                          flag to display help message and exit

Example:

    ftdmp-score --input docking_results_table.txt --monomers-prefix monomers/ \
      --processors 16 --voronota-js-path ~/git/voronota/expansion_js

EOF
exit 1
}

readonly ZEROARG=$0

if [ -z "$1" ]
then
	print_help_and_exit
fi

if [[ $ZEROARG == *"/"* ]]
then
	cd $(dirname $ZEROARG)
	export PATH=$(pwd):$PATH
	cd - &> /dev/null
fi

INFILE=""
MONOMERS_PREFIX=""
PARALLEL_PARTS="1"
VORONOTA_JS_PATH=""
HELP_MODE="false"

while [[ $# > 0 ]]
do
	OPTION="$1"
	OPTARG="$2"
	shift
	case $OPTION in
	--input)
		INFILE="$OPTARG"
		shift
		;;
	--monomers-prefix)
		MONOMERS_PREFIX="$OPTARG"
		shift
		;;
	--parallel-parts)
		PARALLEL_PARTS="$OPTARG"
		shift
		;;
	--voronota-js-path)
		VORONOTA_JS_PATH="$OPTARG"
		shift
		;;
	-h|--help)
		HELP_MODE="true"
		;;
	*)
		echo >&2 "Error: invalid command line option '$OPTION'"
		exit 1
		;;
	esac
done

if [ "$HELP_MODE" == "true" ]
then
	print_help_and_exit
fi

if [ -z "$INFILE" ]
then
	echo >&2 "Error: no input file specified"
	exit 1
fi

if [ ! -s "$INFILE" ]
then
	echo >&2 "Error: no input file '$INFILE1'"
	exit 1
fi

if [ -z "$PARALLEL_PARTS" ] || [ "$PARALLEL_PARTS" -ne "$PARALLEL_PARTS" ] || [ "$PARALLEL_PARTS" -lt "1" ]
then
	echo >&2 "Error: invalid number of parallel parts '$PARALLEL_PARTS', must be a positive number"
	exit 1
fi

if [ -n "$VORONOTA_JS_PATH" ]
then
	export PATH=${VORONOTA_JS_PATH}:${PATH}
fi

command -v voronota-js-fast-iface-voromqa &> /dev/null || { echo >&2 "Error: 'voronota-js-fast-iface-voromqa' executable not in binaries path"; exit 1; }

readonly TMPLDIR=$(mktemp -d)
trap "rm -r $TMPLDIR" EXIT

cat "$INFILE" > "${TMPLDIR}/input"

mkdir -p "${TMPLDIR}/docklines"

cd "${TMPLDIR}/docklines"

cat ../input \
| awk -v mprefix="$MONOMERS_PREFIX" '{if($4!="totalspan"){print "import-docking-result -static-file " mprefix $2 " -mobile-file " mprefix $3 " -ftdock-transform " ($4/$5) " " $7 " " $8 " " $9 " " $10 " " $11 " " $12}}' \
| split -l 1 --numeric-suffixes=1 -a 10

cd - &> /dev/null

find "${TMPLDIR}/docklines" -type f -not -empty \
| voronota-js-fast-iface-voromqa --input _list --input-is-script --processors "$PARALLEL_PARTS" \
| sed 's/^x0\+//'

