#!/bin/bash

function print_help_and_exit
{
cat >&2 << 'EOF'

'ftdmp-all-score' scores complex structures of proteins or nucleic acids

Options:
    --input-from-table        string     input table file path, default is '_stdin' to read from standard input
    --input-from-dir          string     directory path to search for input files, default is ''
    --input-from-pdb          string     multi-model PDB file path to extract input files, default is ''
    --structure-prefix        string     input structure file path prefix, default is ''
    --structure-suffix        string     input structure file path suffix, default is ''
    --structure-monomer1      string     static monomer structure input file path, default is ''
    --structure-monomer2      string     mobile monomer structure input file path, default is ''
    --subselect-contacts      string     query to subselect inter-chain contacts for scoring, default is '[]'
    --reference               string     input structure file to compute CAD-score with, default is ''
    --remap-cadscore          string     flag to use optimal chains remapping for CAD-score, default is 'false'
    --scoring-modes           string  *  scoring modes
    --score-symmetry          string     flag to score symmetry, default is 'false'
    --keep-top                number     number of top complexes to keep after first full scoring stage, default is 1000
    --parallel                number     number of processes to run when scoring, default is 8
    --sbatch                  string     sbatch parameters to run scoring in parallel, default is ''
    --output-names-prefix     string     output names prefix, default is ''
    --output-dir              string  *  output directory path
    --help | -h                          flag to display help message and exit

Examples:

    cat docking_results.txt | ftdmp-score --structure-prefix './complexes/'
      --scoring-modes 'standard_for_protein_protein' --output-dir './results'

EOF
exit 1
}

################################################################################

function compute_hash_of_input_structures
{
	TABLE_FILE="$1"
	TABLE_HEAD_LINES_TO_KEEP="$2"
	TABLE_INPUT_PREFIX="$3"
	TABLE_INPUT_SUFFIX="$4"
	TABLE_MONOMERFILE1="$5"
	TABLE_MONOMERFILE2="$6"
	
	{
		cat "$TABLE_FILE" | head -n "$TABLE_HEAD_LINES_TO_KEEP"
		if [ -n "$TABLE_MONOMERFILE1" ]
		then
			cat "$TABLE_MONOMERFILE1"
			cat "$TABLE_MONOMERFILE2"
		else
			cat "$TABLE_FILE" \
			| awk -v prefix="$TABLE_INPUT_PREFIX" -v suffix="$TABLE_INPUT_SUFFIX" '{if($1!="ID"){print prefix $1 suffix}}' \
			| sort \
			| xargs -L 1000 cat
		fi
	} \
	| sha256sum
}

################################################################################

if [ -z "$1" ]
then
	print_help_and_exit
fi

if [ -z "$FTDMPDIR" ]
then
	export FTDMPDIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
	export PATH="${FTDMPDIR}/core/voronota-js_release:${FTDMPDIR}:${PATH}"
fi

FROM_TABLE="_stdin"
FROM_DIR=""
FROM_PDB=""
INPUT_PREFIX=""
INPUT_SUFFIX=""
MONOMERFILE1=""
MONOMERFILE2=""
SCORENAME_PREFIX=""
INTERFACE_SUBSELECTION="[]"
REFERENCE_STRUCTURE_FILE_FOR_COMPARISON=""
SCORING_PROCESSORS="8"
SCORING_SBATCH=""
SCORE_SYMMETRY="false"
REMAP_CADSCORE="false"
SCORING_TOP_STAGE1="1000"
SCORING_MODES=""
OUTPUT_PATH=""
HELP_MODE="false"

while [[ $# > 0 ]]
do
	OPTION="$1"
	OPTARG="$2"
	shift
	case $OPTION in
	--input-from-table)
		FROM_TABLE="$OPTARG"
		shift
		;;
	--input-from-dir)
		FROM_DIR="$OPTARG"
		shift
		;;
	--input-from-pdb)
		FROM_PDB="$OPTARG"
		shift
		;;
	--structure-prefix)
		INPUT_PREFIX="$OPTARG"
		shift
		;;
	--structure-suffix)
		INPUT_SUFFIX="$OPTARG"
		shift
		;;
	--structure-monomer1)
		MONOMERFILE1="$OPTARG"
		shift
		;;
	--structure-monomer2)
		MONOMERFILE2="$OPTARG"
		shift
		;;
	--output-names-prefix)
		SCORENAME_PREFIX="$OPTARG"
		shift
		;;		
	--subselect-contacts)
		INTERFACE_SUBSELECTION="$OPTARG"
		shift
		;;
	--reference)
		REFERENCE_STRUCTURE_FILE_FOR_COMPARISON="$OPTARG"
		shift
		;;
	--parallel)
		SCORING_PROCESSORS="$OPTARG"
		shift
		;;
	--sbatch)
		SCORING_SBATCH="$OPTARG"
		shift
		;;
	--score-symmetry)
		SCORE_SYMMETRY="$OPTARG"
		shift
		;;
	--remap-cadscore)
		REMAP_CADSCORE="$OPTARG"
		shift
		;;
	--keep-top)
		SCORING_TOP_STAGE1="$OPTARG"
		shift
		;;
	--scoring-modes)
		SCORING_MODES="$OPTARG"
		shift
		;;
	--output-dir)
		OUTPUT_PATH="$OPTARG"
		shift
		;;
	-h|--help)
		HELP_MODE="true"
		;;
	*)
		echo >&2 "Error: invalid command line option '$OPTION'"
		exit 1
		;;
	esac
done

if [ "$HELP_MODE" == "true" ]
then
	print_help_and_exit
fi

if [ -n "$FROM_TABLE" ]
then
	if [ -n "$FROM_DIR" ] || [ -n "$FROM_PDB" ]
	then
		echo >&2 "Error: more than one input source specified"
		exit 1
	fi
	
	if [ "$FROM_TABLE" != "_stdin" ] && [ ! -s "$FROM_TABLE" ]
	then
		echo >&2 "Error: input PDB file '$FROM_TABLE' does not exist or is empty"
		exit 1
	fi
fi

if [ -n "$FROM_DIR" ]
then
	if [ -n "$FROM_TABLE" ] || [ -n "$FROM_PDB" ]
	then
		echo >&2 "Error: more than one input source specified"
		exit 1
	fi
	
	if [ -n "$MONOMERFILE1" ]
	then
		echo >&2 "Error: input directory specified together with monomers"
		exit 1
	fi
	
	if [ -n "$INPUT_PREFIX" ]
	then
		echo >&2 "Error: input directory specified together with input prefix"
		exit 1
	fi
	
	if [ ! -d "$FROM_DIR" ]
	then
		echo >&2 "Error: input directory '$FROM_DIR' does not exist"
		exit 1
	fi
	
	if [ "$(ls "$FROM_DIR" | wc -l)" -lt "1" ]
	then
		echo >&2 "Error: input directory '$FROM_DIR' has no files"
		exit 1
	fi
fi

if [ -n "$FROM_PDB" ]
then
	if [ -n "$FROM_TABLE" ] || [ -n "$FROM_DIR" ]
	then
		echo >&2 "Error: more than one input source specified"
		exit 1
	fi
	
	if [ -n "$MONOMERFILE1" ]
	then
		echo >&2 "Error: input PDB file specified together with monomers"
		exit 1
	fi
	
	if [ -n "$INPUT_PREFIX" ]
	then
		echo >&2 "Error: input PDB file specified together with input prefix"
		exit 1
	fi
	
	if [ ! -s "$FROM_PDB" ]
	then
		echo >&2 "Error: input PDB file '$FROM_PDB' does not exist or is empty"
		exit 1
	fi
fi

if [ -n "${MONOMERFILE1}${MONOMERFILE2}" ] && [ -n "$INPUT_PREFIX" ]
then
	echo >&2 "Error: monomers specified together with input prefix"
	exit 1
fi

if [ -n "$MONOMERFILE1" ] && [ -z "$MONOMERFILE2" ]
then
	echo >&2 "Error: only static monomer specified"
	exit 1
fi

if [ -z "$MONOMERFILE1" ] && [ -n "$MONOMERFILE2" ]
then
	echo >&2 "Error: only mobile monomer specified"
	exit 1
fi

if [ -n "$REFERENCE_STRUCTURE_FILE_FOR_COMPARISON" ] && [ ! -s "$REFERENCE_STRUCTURE_FILE_FOR_COMPARISON" ]
then
	echo >&2 "Error: input structure file for comparison '$REFERENCE_STRUCTURE_FILE_FOR_COMPARISON' does not exist or is empty"
	exit 1
fi

[ -n "$INTERFACE_SUBSELECTION" ] || { echo >&2 "Error: contacts subselection not defined"; exit 1; }

[ -n "$SCORING_MODES" ] || { echo >&2 "Error: scoring modes not provided"; exit 1;}

[ -n "$OUTPUT_PATH" ] || { echo >&2 "Error: output path not provided"; exit 1;}

################################################################################

SCORING_MODE_PROTEIN="false"
SCORING_MODE_PROTEIN_SIDECHAIN_REBUILT="false"
SCORING_MODE_GENERIC="false"
SCORING_MODE_GENERIC_SIDECHAIN_REBUILT="false"

if [ "$SCORING_MODES" == "all" ]
then
	SCORING_MODE_PROTEIN="true"
	SCORING_MODE_PROTEIN_SIDECHAIN_REBUILT="true"
	SCORING_MODE_GENERIC="true"
	SCORING_MODE_GENERIC_SIDECHAIN_REBUILT="true"
fi

if [[ "$SCORING_MODES" == *"[protein]"* ]]
then
	SCORING_MODE_PROTEIN="true"
fi

if [[ "$SCORING_MODES" == *"[protein_sr]"* ]]
then
	SCORING_MODE_PROTEIN_SIDECHAIN_REBUILT="true"
fi

if [[ "$SCORING_MODES" == *"[generic]"* ]]
then
	SCORING_MODE_GENERIC="true"
fi

if [[ "$SCORING_MODES" == *"[generic_sr]"* ]]
then
	SCORING_MODE_GENERIC_SIDECHAIN_REBUILT="true"
fi

################################################################################

if [ -z "$REFERENCE_STRUCTURE_FILE_FOR_COMPARISON" ] && [ "$SCORING_MODE_PROTEIN" != "true" ] && [ "$SCORING_MODE_PROTEIN_SIDECHAIN_REBUILT" != "true" ] && [ "$SCORING_MODE_GENERIC" != "true" ] && [ "$SCORING_MODE_GENERIC_SIDECHAIN_REBUILT" != "true" ]
then
	echo >&2 "Error: no scoring actions specified"
	exit 1
fi

################################################################################

mkdir -p "$OUTPUT_PATH"

NEXT_SCORING_RESULTS_FILE="${OUTPUT_PATH}/${SCORENAME_PREFIX}scoring_input.txt"

if [ -n "$FROM_TABLE" ]
then
	if [ "$FROM_TABLE" == "_stdin" ]
	then
		cat > "$NEXT_SCORING_RESULTS_FILE"
	else
		if [ "$(dirname "$FROM_TABLE")" == "$(dirname "$NEXT_SCORING_RESULTS_FILE")" ]
		then
			NEXT_SCORING_RESULTS_FILE="$FROM_TABLE"
		else
			cat "$FROM_TABLE" > "$NEXT_SCORING_RESULTS_FILE"
		fi
	fi
else
	if [ -n "$FROM_PDB" ]
	then
		ftdmp-split-pdb --input "$FROM_PDB" --output-prefix "${OUTPUT_PATH}/models/model" --output-suffix ".pdb" > /dev/null
		FROM_DIR="${OUTPUT_PATH}/models"
	fi
	
	if [ -n "$FROM_DIR" ]
	then
		INPUT_PREFIX="${FROM_DIR}/"
		INPUT_SUFFIX=""
		{
		echo ID
		ls "$FROM_DIR"
		} > "$NEXT_SCORING_RESULTS_FILE"
	fi
fi

if [ ! -s "$NEXT_SCORING_RESULTS_FILE" ]
then
	echo >&2 "Error: no input data"
	exit 1
fi

if [ "$(cat "$NEXT_SCORING_RESULTS_FILE" | head -1 | awk '{print $1}')" != "ID" ]
then
	TMP_NEXT_SCORING_RESULTS_FILE="${OUTPUT_PATH}/${SCORENAME_PREFIX}scoring_input_prepared.txt"
	
	{
	echo "ID"
	cat "$NEXT_SCORING_RESULTS_FILE" | awk '{print $1}'
	} > "$TMP_NEXT_SCORING_RESULTS_FILE"
	
	mv "$TMP_NEXT_SCORING_RESULTS_FILE" "$NEXT_SCORING_RESULTS_FILE"
fi

PREV_SCORING_RESULTS_FILE="$NEXT_SCORING_RESULTS_FILE"

HEAD_LINES_TO_KEEP=9999999

################################################################################

if [ -n "$REFERENCE_STRUCTURE_FILE_FOR_COMPARISON" ]
then
	NEXT_SCORING_RESULTS_FILE="${OUTPUT_PATH}/${SCORENAME_PREFIX}scoring_results_FICS.txt"
	
	{
	compute_hash_of_input_structures "$PREV_SCORING_RESULTS_FILE" "$HEAD_LINES_TO_KEEP" "$INPUT_PREFIX" "$INPUT_SUFFIX" "$MONOMERFILE1" "$MONOMERFILE2"
	cat "$REFERENCE_STRUCTURE_FILE_FOR_COMPARISON"
	echo "$INTERFACE_SUBSELECTION"
	echo "$REMAP_CADSCORE"
	} | ftdmp-check-hash --hash-file "${OUTPUT_PATH}/input_hashes/$(basename "$NEXT_SCORING_RESULTS_FILE")" --dependent-file "$NEXT_SCORING_RESULTS_FILE"
	
	if [ ! -s "$NEXT_SCORING_RESULTS_FILE" ]
	then
		cat "$PREV_SCORING_RESULTS_FILE" | head -n "$HEAD_LINES_TO_KEEP" \
		| ftdmp-calc-interface-cadscore-for-reference \
		  --input-prefix "$INPUT_PREFIX" --input-suffix "$INPUT_SUFFIX" \
		  --monomer1 "$MONOMERFILE1" --monomer2 "$MONOMERFILE2" \
		  --reference "$REFERENCE_STRUCTURE_FILE_FOR_COMPARISON" \
		  --subselect-contacts "$INTERFACE_SUBSELECTION" \
		  --remap-chains "$REMAP_CADSCORE" \
		  --parallel "$SCORING_PROCESSORS" --sbatch-parameters "$SCORING_SBATCH" \
		  --colnames-prefix "${SCORENAME_PREFIX}FICS_" \
		  --adjoin \
		| ftdmp-sort-table --columns "${SCORENAME_PREFIX}FICS_iface_cadscore" \
		> "$NEXT_SCORING_RESULTS_FILE"
	fi
	
	PREV_SCORING_RESULTS_FILE="$NEXT_SCORING_RESULTS_FILE"
fi

################################################################################

if [ "$SCORING_MODE_PROTEIN" == "true" ]
then
	NEXT_SCORING_RESULTS_FILE="${OUTPUT_PATH}/${SCORENAME_PREFIX}scoring_results_FIV.txt"
	
	{
	compute_hash_of_input_structures "$PREV_SCORING_RESULTS_FILE" "$HEAD_LINES_TO_KEEP" "$INPUT_PREFIX" "$INPUT_SUFFIX" "$MONOMERFILE1" "$MONOMERFILE2"
	echo "$INTERFACE_SUBSELECTION"
	echo "$SCORE_SYMMETRY"
	} | ftdmp-check-hash --hash-file "${OUTPUT_PATH}/input_hashes/$(basename "$NEXT_SCORING_RESULTS_FILE")" --dependent-file "$NEXT_SCORING_RESULTS_FILE"
	
	if [ ! -s "$NEXT_SCORING_RESULTS_FILE" ]
	then
		cat "$PREV_SCORING_RESULTS_FILE" | head -n "$HEAD_LINES_TO_KEEP" \
		| ftdmp-calc-interface-voromqa-scores \
		  --input-prefix "$INPUT_PREFIX" --input-suffix "$INPUT_SUFFIX" \
		  --monomer1 "$MONOMERFILE1" --monomer2 "$MONOMERFILE2" \
		  --subselect-contacts "$INTERFACE_SUBSELECTION" \
		  --parallel "$SCORING_PROCESSORS" --sbatch-parameters "$SCORING_SBATCH" \
		  --score-symmetry "$SCORE_SYMMETRY" \
		  --colnames-prefix "${SCORENAME_PREFIX}FIV_" \
		  --adjoin \
		| ftdmp-sort-table --columns "-${SCORENAME_PREFIX}FIV_iface_energy" \
		> "$NEXT_SCORING_RESULTS_FILE"
	fi
	
	PREV_SCORING_RESULTS_FILE="$NEXT_SCORING_RESULTS_FILE"
	HEAD_LINES_TO_KEEP="$((SCORING_TOP_STAGE1+1))"
fi

################################################################################

if [ "$SCORING_MODE_GENERIC" == "true" ]
then
	NEXT_SCORING_RESULTS_FILE="${OUTPUT_PATH}/${SCORENAME_PREFIX}scoring_results_FIVb.txt"
	
	{
	compute_hash_of_input_structures "$PREV_SCORING_RESULTS_FILE" "$HEAD_LINES_TO_KEEP" "$INPUT_PREFIX" "$INPUT_SUFFIX" "$MONOMERFILE1" "$MONOMERFILE2"
	echo "$INTERFACE_SUBSELECTION"
	echo "$SCORE_SYMMETRY"
	} | ftdmp-check-hash --hash-file "${OUTPUT_PATH}/input_hashes/$(basename "$NEXT_SCORING_RESULTS_FILE")" --dependent-file "$NEXT_SCORING_RESULTS_FILE"
	
	if [ ! -s "$NEXT_SCORING_RESULTS_FILE" ]
	then
		cat "$PREV_SCORING_RESULTS_FILE" | head -n "$HEAD_LINES_TO_KEEP" \
		| ftdmp-calc-interface-voromqa-scores \
		  --input-prefix "$INPUT_PREFIX" --input-suffix "$INPUT_SUFFIX" \
		  --monomer1 "$MONOMERFILE1" --monomer2 "$MONOMERFILE2" \
		  --subselect-contacts "$INTERFACE_SUBSELECTION" \
		  --parallel "$SCORING_PROCESSORS" --sbatch-parameters "$SCORING_SBATCH" \
		  --blanket \
		  --score-symmetry "$SCORE_SYMMETRY" \
		  --colnames-prefix "${SCORENAME_PREFIX}FIVb_" \
		  --adjoin \
		| ftdmp-sort-table --columns "-${SCORENAME_PREFIX}FIVb_iface_energy" \
		> "$NEXT_SCORING_RESULTS_FILE"
	fi
	
	PREV_SCORING_RESULTS_FILE="$NEXT_SCORING_RESULTS_FILE"
	HEAD_LINES_TO_KEEP="$((SCORING_TOP_STAGE1+1))"
fi

################################################################################

if [ "$SCORING_MODE_PROTEIN_SIDECHAIN_REBUILT" == "true" ]
then
	NEXT_SCORING_RESULTS_FILE="${OUTPUT_PATH}/${SCORENAME_PREFIX}scoring_results_FIV_sr.txt"
	
	{
	compute_hash_of_input_structures "$PREV_SCORING_RESULTS_FILE" "$HEAD_LINES_TO_KEEP" "$INPUT_PREFIX" "$INPUT_SUFFIX" "$MONOMERFILE1" "$MONOMERFILE2"
	echo "$INTERFACE_SUBSELECTION"
	} | ftdmp-check-hash --hash-file "${OUTPUT_PATH}/input_hashes/$(basename "$NEXT_SCORING_RESULTS_FILE")" --dependent-file "$NEXT_SCORING_RESULTS_FILE"
	
	if [ ! -s "$NEXT_SCORING_RESULTS_FILE" ]
	then
		cat "$PREV_SCORING_RESULTS_FILE" | head -n "$HEAD_LINES_TO_KEEP" \
		| ftdmp-calc-interface-voromqa-scores \
		  --input-prefix "$INPUT_PREFIX" --input-suffix "$INPUT_SUFFIX" \
		  --monomer1 "$MONOMERFILE1" --monomer2 "$MONOMERFILE2" \
		  --subselect-contacts "$INTERFACE_SUBSELECTION" \
		  --parallel "$SCORING_PROCESSORS" --sbatch-parameters "$SCORING_SBATCH" \
		  --rebuild-sidechains \
		  --colnames-prefix "${SCORENAME_PREFIX}FIV_sr_" \
		  --adjoin \
		| ftdmp-sort-table --columns "-${SCORENAME_PREFIX}FIV_sr_iface_energy" \
		> "$NEXT_SCORING_RESULTS_FILE"
	fi
	
	PREV_SCORING_RESULTS_FILE="$NEXT_SCORING_RESULTS_FILE"
	HEAD_LINES_TO_KEEP="$((SCORING_TOP_STAGE1+1))"
fi

################################################################################

if [ "$SCORING_MODE_GENERIC_SIDECHAIN_REBUILT" == "true" ]
then
	NEXT_SCORING_RESULTS_FILE="${OUTPUT_PATH}/${SCORENAME_PREFIX}scoring_results_FIVb_sr.txt"

	{
	compute_hash_of_input_structures "$PREV_SCORING_RESULTS_FILE" "$HEAD_LINES_TO_KEEP" "$INPUT_PREFIX" "$INPUT_SUFFIX" "$MONOMERFILE1" "$MONOMERFILE2"
	echo "$INTERFACE_SUBSELECTION"
	} | ftdmp-check-hash --hash-file "${OUTPUT_PATH}/input_hashes/$(basename "$NEXT_SCORING_RESULTS_FILE")" --dependent-file "$NEXT_SCORING_RESULTS_FILE"
	
	if [ ! -s "$NEXT_SCORING_RESULTS_FILE" ]
	then
		cat "$PREV_SCORING_RESULTS_FILE" | head -n "$HEAD_LINES_TO_KEEP" \
		| ftdmp-calc-interface-voromqa-scores \
		  --input-prefix "$INPUT_PREFIX" --input-suffix "$INPUT_SUFFIX" \
		  --monomer1 "$MONOMERFILE1" --monomer2 "$MONOMERFILE2" \
		  --subselect-contacts "$INTERFACE_SUBSELECTION" \
		  --parallel "$SCORING_PROCESSORS" --sbatch-parameters "$SCORING_SBATCH" \
		  --blanket --rebuild-sidechains \
		  --colnames-prefix "${SCORENAME_PREFIX}FIVb_sr_" \
		  --adjoin \
		| ftdmp-sort-table --columns "-${SCORENAME_PREFIX}FIVb_sr_iface_energy" \
		> "$NEXT_SCORING_RESULTS_FILE"
	fi
	
	PREV_SCORING_RESULTS_FILE="$NEXT_SCORING_RESULTS_FILE"
	HEAD_LINES_TO_KEEP="$((SCORING_TOP_STAGE1+1))"
fi

################################################################################

NEXT_SCORING_RESULTS_FILE="${OUTPUT_PATH}/${SCORENAME_PREFIX}scoring_results.txt"

{
cat "$PREV_SCORING_RESULTS_FILE"
echo "$SCORING_MODE_PROTEIN"
echo "$SCORING_MODE_GENERIC"
echo "$SCORING_MODE_PROTEIN_SIDECHAIN_REBUILT"
echo "$SCORING_MODE_GENERIC_SIDECHAIN_REBUILT"
} | ftdmp-check-hash --hash-file "${OUTPUT_PATH}/input_hashes/$(basename "$NEXT_SCORING_RESULTS_FILE")" --dependent-file "$NEXT_SCORING_RESULTS_FILE"

if [ ! -s "$NEXT_SCORING_RESULTS_FILE" ]
then
	cat "$PREV_SCORING_RESULTS_FILE" \
	| {
		if [ "$SCORING_MODE_PROTEIN" == "true" ]
		then
			ftdmp-sort-table \
			  --columns "-${SCORENAME_PREFIX}FIV_iface_energy" \
			  --add-rank-column "${SCORENAME_PREFIX}FIV_iface_energy_rank" \
			| ftdmp-sort-table \
			  --columns "-${SCORENAME_PREFIX}FIV_iface_energy_norm" \
			  --add-rank-column "${SCORENAME_PREFIX}FIV_iface_energy_norm_rank" \
			| ftdmp-sort-table \
			  --columns "-${SCORENAME_PREFIX}FIV_iface_energy -${SCORENAME_PREFIX}FIV_iface_clash_score" \
			  --tolerances "0 0.05" \
			  --add-rank-column "${SCORENAME_PREFIX}FIV_energy_clash_tour_rank" \
			| ftdmp-sort-table \
			  --columns "-${SCORENAME_PREFIX}FIV_iface_energy -${SCORENAME_PREFIX}FIV_iface_energy_norm -${SCORENAME_PREFIX}FIV_iface_clash_score" \
			  --tolerances "0 0 0.05" \
			  --add-rank-column "${SCORENAME_PREFIX}FIV_energy_norm_clash_tour_rank"
		else
			cat
		fi
	} \
	| {
		if [ "$SCORING_MODE_GENERIC" == "true" ]
		then
			ftdmp-sort-table \
			  --columns "-${SCORENAME_PREFIX}FIVb_iface_energy" \
			  --add-rank-column "${SCORENAME_PREFIX}FIVb_iface_energy_rank" \
			| ftdmp-sort-table \
			  --columns "-${SCORENAME_PREFIX}FIVb_iface_energy_norm" \
			  --add-rank-column "${SCORENAME_PREFIX}FIVb_iface_energy_norm_rank" \
			| ftdmp-sort-table \
			  --columns "-${SCORENAME_PREFIX}FIVb_iface_energy -${SCORENAME_PREFIX}FIVb_iface_clash_score" \
			  --tolerances "0 0.05" \
			  --add-rank-column "${SCORENAME_PREFIX}FIVb_energy_clash_tour_rank" \
			| ftdmp-sort-table \
			  --columns "-${SCORENAME_PREFIX}FIVb_iface_energy -${SCORENAME_PREFIX}FIVb_iface_energy_norm -${SCORENAME_PREFIX}FIVb_iface_clash_score" \
			  --tolerances "0 0 0.05" \
			  --add-rank-column "${SCORENAME_PREFIX}FIVb_energy_norm_clash_tour_rank"
		else
			cat
		fi
	} \
	| {
		if [ "$SCORING_MODE_PROTEIN_SIDECHAIN_REBUILT" == "true" ]
		then
			ftdmp-sort-table \
			  --columns "-${SCORENAME_PREFIX}FIV_sr_iface_energy" \
			  --add-rank-column "${SCORENAME_PREFIX}FIV_sr_iface_energy_rank" \
			| ftdmp-sort-table \
			  --columns "-${SCORENAME_PREFIX}FIV_sr_iface_energy_norm" \
			  --add-rank-column "${SCORENAME_PREFIX}FIV_sr_iface_energy_norm_rank" \
			| ftdmp-sort-table \
			  --columns "-${SCORENAME_PREFIX}FIV_sr_iface_energy -${SCORENAME_PREFIX}FIV_sr_iface_clash_score" \
			  --tolerances "0 0.05" \
			  --add-rank-column "${SCORENAME_PREFIX}FIV_sr_energy_clash_tour_rank" \
			| ftdmp-sort-table \
			  --columns "-${SCORENAME_PREFIX}FIV_sr_iface_energy -${SCORENAME_PREFIX}FIV_sr_iface_energy_norm -${SCORENAME_PREFIX}FIV_sr_iface_clash_score" \
			  --tolerances "0 0 0.05" \
			  --add-rank-column "${SCORENAME_PREFIX}FIV_sr_energy_norm_clash_tour_rank"
		else
			cat
		fi
	} \
	| {
		if [ "$SCORING_MODE_GENERIC_SIDECHAIN_REBUILT" == "true" ]
		then
			ftdmp-sort-table \
			  --columns "-${SCORENAME_PREFIX}FIVb_sr_iface_energy" \
			  --add-rank-column "${SCORENAME_PREFIX}FIVb_sr_iface_energy_rank" \
			| ftdmp-sort-table \
			  --columns "-${SCORENAME_PREFIX}FIVb_sr_iface_energy_norm" \
			  --add-rank-column "${SCORENAME_PREFIX}FIVb_sr_iface_energy_norm_rank" \
			| ftdmp-sort-table \
			  --columns "-${SCORENAME_PREFIX}FIVb_sr_iface_energy -${SCORENAME_PREFIX}FIVb_sr_iface_clash_score" \
			  --tolerances "0 0.05" \
			  --add-rank-column "${SCORENAME_PREFIX}FIVb_sr_energy_clash_tour_rank" \
			| ftdmp-sort-table \
			  --columns "-${SCORENAME_PREFIX}FIVb_sr_iface_energy -${SCORENAME_PREFIX}FIVb_sr_iface_energy_norm -${SCORENAME_PREFIX}FIVb_sr_iface_clash_score" \
			  --tolerances "0 0 0.05" \
			  --add-rank-column "${SCORENAME_PREFIX}FIVb_sr_energy_norm_clash_tour_rank"
		else
			cat
		fi
	} \
	> "$NEXT_SCORING_RESULTS_FILE"
fi

PREV_SCORING_RESULTS_FILE="$NEXT_SCORING_RESULTS_FILE"

################################################################################
