#!/bin/bash

function print_help_and_exit
{
cat >&2 << 'EOF'

'ftdmp-calc-interface-gnn-scores' evaluates docking results produced by 'ftdmp-dock'

Options:
    --input-prefix            string     input file path prefix
    --input-suffix            string     input file path suffix, default is '.pdb'
    --monomer1                string     static monomer input file path
    --monomer2                string     mobile monomer input file path
    --subselect-contacts      string     query to subselect inter-chain contacts, default is '[]'
    --conda-path              string     conda installation path, default is ''
    --conda-env               string     conda environment name, default is ''
    --rebuild-sidechains                 flag to rebuild sidechains using FASPR
    --local-column            string     flag to add per-residue scores to the global output table
    --parallel                number     total number of parallel parts, default is 1
    --cache-dir               string     cache directory path to store results of past calculations
    --colnames-prefix         string     prefix for output column names, default is 'FIGNN_'
    --adjoin                             flag to output results joined with input
    --help | -h                          flag to display help message and exit

Standard input:
    space-separated table of docking results

Standard output:
    space-separated table of scoring results
    
Example:

    cat docking_results_table.txt | ftdmp-calc-interface-gnn-scores -m1 monomer1.pdb -m2 monomer2.pdb --parallel 16

EOF
exit 1
}

if [ -z "$1" ]
then
	print_help_and_exit
fi

if [ -z "$FTDMPDIR" ]
then
	export FTDMPDIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
	export PATH="${FTDMPDIR}/core/voronota-iface-gnn_release:${FTDMPDIR}/core/voronota-js_release:${FTDMPDIR}:${PATH}"
fi

command -v voronota-iface-gnn-score &> /dev/null || { echo >&2 "Error: 'voronota-iface-gnn-score' executable not in binaries path"; exit 1; }
command -v voronota-js-fast-iface-data-graph &> /dev/null || { echo >&2 "Error: 'voronota-js-fast-iface-data-graph' executable not in binaries path"; exit 1; }

INPUT_PREFIX=""
INPUT_SUFFIX=".pdb"
MONOMERFILE1=""
MONOMERFILE2=""
CONDA_PATH=""
CONDA_ENV=""
PARALLEL_PARTS="1"
CACHE_DIR=""
SUBSELECT_CONTACTS="[]"
COLNAMES_PREFIX="FIGNN_"
USE_MONOMERS="false"
ADJOIN="false"
REBUILD_SIDECHAINS="false"
LOCAL_COLUMN="false"
HELP_MODE="false"

while [[ $# > 0 ]]
do
	OPTION="$1"
	OPTARG="$2"
	shift
	case $OPTION in
	--input-prefix)
		INPUT_PREFIX="$OPTARG"
		shift
		;;
	--input-suffix)
		INPUT_SUFFIX="$OPTARG"
		shift
		;;
	--monomer1)
		MONOMERFILE1="$OPTARG"
		USE_MONOMERS="true"
		shift
		;;
	--monomer2)
		MONOMERFILE2="$OPTARG"
		USE_MONOMERS="true"
		shift
		;;
	--conda-path)
		CONDA_PATH="$OPTARG"
		shift
		;;
	--conda-env)
		CONDA_ENV="$OPTARG"
		shift
		;;
	--parallel)
		PARALLEL_PARTS="$OPTARG"
		shift
		;;
	--cache-dir)
		CACHE_DIR="$OPTARG"
		shift
		;;
	--subselect-contacts)
		SUBSELECT_CONTACTS="$OPTARG"
		shift
		;;
	--colnames-prefix)
		COLNAMES_PREFIX="$OPTARG"
		shift
		;;
	--adjoin)
		ADJOIN="true"
		;;
	--rebuild-sidechains)
		REBUILD_SIDECHAINS="true"
		;;
	--local-column)
		LOCAL_COLUMN="$OPTARG"
		shift
		;;
	-h|--help)
		HELP_MODE="true"
		;;
	*)
		echo >&2 "Error: invalid command line option '$OPTION'"
		exit 1
		;;
	esac
done

if [ "$HELP_MODE" == "true" ]
then
	print_help_and_exit
fi

if [ -z "$MONOMERFILE1" ] && [ -z "$MONOMERFILE2" ]
then
	USE_MONOMERS="false"
fi

if [ "$USE_MONOMERS" == "true" ]
then
	if [ -z "$MONOMERFILE1" ]
	then
		echo >&2 "Error: no static input file specified"
		exit 1
	fi
	
	if [ ! -s "$MONOMERFILE1" ]
	then
		echo >&2 "Error: no static input file '$MONOMERFILE1'"
		exit 1
	fi
	
	if [ -z "$MONOMERFILE2" ]
	then
		echo >&2 "Error: no mobile input file specified"
		exit 1
	fi
	
	if [ ! -s "$MONOMERFILE2" ]
	then
		echo >&2 "Error: no mobile input file '$MONOMERFILE2'"
		exit 1
	fi
fi

if [ -z "$PARALLEL_PARTS" ] || [ "$PARALLEL_PARTS" -ne "$PARALLEL_PARTS" ] || [ "$PARALLEL_PARTS" -lt "1" ]
then
	echo >&2 "Error: invalid number of parallel parts '$PARALLEL_PARTS', must be a positive number"
	exit 1
fi

if [ -z "$FTDMPDIR" ]
then
	echo >&2 "Error: no defined environmental variable FTDMPDIR"
	exit 1
fi

GNN_PACKAGES_PATH="${FTDMPDIR}/core/voronota-iface-gnn_release/gnn_packages/v1"

if [ ! -d "${GNN_PACKAGES_PATH}" ]
then
	echo >&2 "Error: no GNN packages directory '$GNN_PACKAGES_PATH'"
	exit 1
fi

if [ ! -s "${GNN_PACKAGES_PATH}/gnn1.tar" ]
then
	echo >&2 "Error: no first GNN package '${GNN_PACKAGES_PATH}/gnn1.tar'"
	exit 1
fi

MORE_IFACE_GNN_PARAMETERS=()

MORE_IFACE_GNN_PARAMETERS+=("--gnn")
MORE_IFACE_GNN_PARAMETERS+=("$GNN_PACKAGES_PATH")
MORE_IFACE_GNN_PARAMETERS+=("--conda-path")
MORE_IFACE_GNN_PARAMETERS+=("$CONDA_PATH")
MORE_IFACE_GNN_PARAMETERS+=("--conda-env")
MORE_IFACE_GNN_PARAMETERS+=("$CONDA_ENV")
MORE_IFACE_GNN_PARAMETERS+=("--processors")
MORE_IFACE_GNN_PARAMETERS+=("$PARALLEL_PARTS")
MORE_IFACE_GNN_PARAMETERS+=("--subselect-contacts")
MORE_IFACE_GNN_PARAMETERS+=("$SUBSELECT_CONTACTS")
MORE_IFACE_GNN_PARAMETERS+=("--local-column")
MORE_IFACE_GNN_PARAMETERS+=("$LOCAL_COLUMN")
MORE_IFACE_GNN_PARAMETERS+=("--cache-dir")
MORE_IFACE_GNN_PARAMETERS+=("$CACHE_DIR")

if [ "$REBUILD_SIDECHAINS" == "true" ]
then
	MORE_IFACE_GNN_PARAMETERS+=("--faspr-path")
	MORE_IFACE_GNN_PARAMETERS+=("${FTDMPDIR}/core/FASPR/FASPR")
	MORE_IFACE_GNN_PARAMETERS+=("--run-faspr")
	MORE_IFACE_GNN_PARAMETERS+=("true")
fi

readonly TMPLDIR=$(mktemp -d)
trap "rm -r $TMPLDIR" EXIT

cat > "${TMPLDIR}/input"

if [ ! -s "${TMPLDIR}/input" ]
then
	echo >&2 "Error: no input data in stdin"
	exit 1
fi

{
if [ "$USE_MONOMERS" == "true" ]
then
	mkdir -p "${TMPLDIR}/docklines"
	
	cd "${TMPLDIR}/docklines"
	
	cat ../input \
	| awk -v m1="$MONOMERFILE1" -v m2="$MONOMERFILE2" '{if($1!="ID"){print "import-docking-result -static-file \"" m1 "\" -mobile-file \"" m2 "\" -generic-transform " $3 " " $4 " " $5 " " $6 " " $7 " " $8 " " $9 " " $10 " " $11 " " $12 " " $13 " " $14 " " $15 > $1}}'
	
	cd - &> /dev/null
	
	find "${TMPLDIR}/docklines" -type f -not -empty \
	| voronota-iface-gnn-score --input _list --input-is-script 'true' "${MORE_IFACE_GNN_PARAMETERS[@]}"
else
	cat "${TMPLDIR}/input" \
	| awk -v prefix="$INPUT_PREFIX" -v suffix="$INPUT_SUFFIX" '{if($1!="ID"){print prefix $1 suffix}}' \
	| voronota-iface-gnn-score --input _list "${MORE_IFACE_GNN_PARAMETERS[@]}" \
	| sed "s/^\(\S\+\)${INPUT_SUFFIX} /\1 /"
fi
} \
| sed '1 s/^\(\S\+\) /ID /' \
| sed "1 s/\s\+/ ${COLNAMES_PREFIX}/g" \
| sed 's/\s\+/ /g' \
> "${TMPLDIR}/output"

if [ ! -s "${TMPLDIR}/output" ]
then
	echo >&2 "Error: no output produced"
	exit 1
fi

if [ "$ADJOIN" == "true" ]
then
	ftdmp-join-tables "${TMPLDIR}/input" "${TMPLDIR}/output"
else
	cat "${TMPLDIR}/output"
fi

