#!/bin/bash

function print_help_and_exit
{
cat >&2 << 'EOF'

'ftdmp-form-capri-answer' forms CAPRI answer from ordered list of files

Options:
    --input-prefix            string     input file path prefix, default is ''
    --input-suffix            string     input file path suffix, default is ''
    --brk                     string  *  input .brk file path
    --output                  string  *  output file path
    --authors                 string  *  authors string
    --force-top-picks         string     space-separated list of picks to put in front
    --align-sel               string     selection of atoms copy to align
    --rename-chains           string     chain renaming rule to apply
    --scoring-set             string     scoring set file path to produce scoring answer, default is ''
    --help | -h                          flag to display help message and exit

Standard input:
    list of structure files or IDs

Standard output:
    list of used structure files
    
Examples:

	(echo file1.pdb ; echo file2.pdb) \
	| ftdmp-form-capri-answer \
	  --brk input/capri.brk --output output/answer.pdb \
	  --align-sel '[-chain A]' --rename-chains 'C=E,D=F'

EOF
exit 1
}

if [ -z "$1" ]
then
	print_help_and_exit
fi

if [ -z "$FTDMPDIR" ]
then
	export FTDMPDIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
	export PATH="${FTDMPDIR}/core/voronota-js_release:${FTDMPDIR}:${PATH}"
fi

command -v voronota-js &> /dev/null || { echo >&2 "Error: 'voronota-js' executable not in binaries path"; exit 1; }

INPUT_PREFIX=""
INPUT_SUFFIX=""
BRKFILE=""
OUTFILE=""
AUTHORS=""
FORCE_TOP_PICKS=""
ALIGN_SEL=""
RENAME_CHAINS=""
SCORING_SET_FILE=""
HELP_MODE="false"

while [[ $# > 0 ]]
do
	OPTION="$1"
	OPTARG="$2"
	shift
	case $OPTION in
	--input-prefix)
		INPUT_PREFIX="$OPTARG"
		shift
		;;
	--input-suffix)
		INPUT_SUFFIX="$OPTARG"
		shift
		;;
	--brk)
		BRKFILE="$OPTARG"
		shift
		;;
	--output)
		OUTFILE="$OPTARG"
		shift
		;;
	--authors)
		AUTHORS="$OPTARG"
		shift
		;;
	--force-top-picks)
		FORCE_TOP_PICKS="$OPTARG"
		shift
		;;
	--align-sel)
		ALIGN_SEL="$OPTARG"
		shift
		;;
	--rename-chains)
		RENAME_CHAINS="$OPTARG"
		shift
		;;
	--scoring-set)
		SCORING_SET_FILE="$OPTARG"
		shift
		;;
	-h|--help)
		HELP_MODE="true"
		;;
	*)
		echo >&2 "Error: invalid command line option '$OPTION'"
		exit 1
		;;
	esac
done

if [ "$HELP_MODE" == "true" ]
then
	print_help_and_exit
fi

if [ -z "$SCORING_SET_FILE" ] && [ -z "$BRKFILE" ]
then
	echo >&2 "Error: neither input .brk file path nor scoring set file path provided"
	exit 1
fi

if [ -z "$OUTFILE" ]
then
	echo >&2 "Error: output file path not provided"
	exit 1
fi

if [ -z "$AUTHORS" ]
then
	echo >&2 "Error: authors not provided"
	exit 1
fi

if [ -z "$SCORING_SET_FILE" ] && [ ! -s "$BRKFILE" ]
then
	echo >&2 "Error: input .brk file '$BRKFILE' does not exist"
	exit 1
fi

if [ -n "$SCORING_SET_FILE" ] && [ ! -s "$SCORING_SET_FILE" ]
then
	echo >&2 "Error: input scoring set file '$SCORING_SET_FILE' does not exist"
	exit 1
fi

readonly TMPLDIR=$(mktemp -d)
trap "rm -r $TMPLDIR" EXIT

cat \
| awk '{if($1!="ID"){print $1}}' \
| egrep . \
| uniq \
> "${TMPLDIR}/input_raw"

if [ ! -s "${TMPLDIR}/input_raw" ]
then
	echo >&2 "Error: no input data in stdin"
	exit 1
fi

if [ -n "$FORCE_TOP_PICKS" ]
then
	echo "$FORCE_TOP_PICKS" | sed 's/\s\+/\n/g' > "${TMPLDIR}/force_top_picks"
	
	{
		cat "${TMPLDIR}/force_top_picks"
		cat "${TMPLDIR}/input_raw" | grep -v -x -F -f "${TMPLDIR}/force_top_picks"
	} \
	| uniq \
	> "${TMPLDIR}/input_raw_forced"
	
	mv "${TMPLDIR}/input_raw_forced" "${TMPLDIR}/input_raw"
fi

cat "${TMPLDIR}/input_raw" \
| awk -v prefix="$INPUT_PREFIX" -v suffix="$INPUT_SUFFIX" '{print prefix $1 suffix}' \
> "${TMPLDIR}/input"

while read -r INFILE
do
	if [ ! -s "$INFILE" ]
	then
		echo >&2 "Error: input structure file '$INFILE' does not exist"
		exit 1
	fi
done < "${TMPLDIR}/input"

NUMBER_OF_MODELS="$(cat "${TMPLDIR}/input" | wc -l)"

{
cat << EOF
var params={}
params.align_sel='$ALIGN_SEL';
params.rename_chains='$RENAME_CHAINS';
params.outprefix='${TMPLDIR}/';
var input_files=[];
EOF

cat "${TMPLDIR}/input" | awk -v q="'" '{print "input_files.push(" q $1 q ");"}'

cat << 'EOF'
for(var i=0;i<input_files.length;i++)
{
	voronota_import("-file", input_files[i], "-title", "model"+i);
	voronota_assert_full_success("Failed to import model file '"+input_files[i]+"'");
}

voronota_pick_objects();

if(params.align_sel)
{
	voronota_tmalign_many("-target", "model0", "-target-sel", params.align_sel, "-model-sel", params.align_sel);
	voronota_assert_full_success("Failed to run tmalign using provided selections");
}

if(params.rename_chains)
{
	voronota_set_chain_name("-chain-name", params.rename_chains);
	voronota_assert_full_success("Failed to rename chains");
}

for(var i=0;i<input_files.length;i++)
{
	voronota_export_atoms("-on-objects", "model"+i, "-file", params.outprefix+"model"+(i+1), "-as-pdb", "-pdb-ter");
	voronota_assert_full_success("Failed to export atoms");
}

EOF
} | voronota-js --no-setup-defaults

if [ ! -s "${TMPLDIR}/model1" ] || [ ! -s "${TMPLDIR}/model${NUMBER_OF_MODELS}" ]
then
	echo >&2 "Error: failed to prepare model files"
	exit 1
fi

mkdir -p "$(dirname "$OUTFILE")"

if [ -z "$SCORING_SET_FILE" ]
then
	{
		cat "$BRKFILE" | egrep '^HEADER|^COMPND'
		
		echo "AUTHOR    $AUTHORS"
		
		cat "$BRKFILE" | egrep '^REMARK|^SEQRES'
		
		seq 1 "$NUMBER_OF_MODELS" \
		| while read MODELNUM
		do
			echo "   $MODELNUM" | sed 's/.*\(....\)$/MODEL \1/'
			echo "PARENT     N/A"
			cat "${TMPLDIR}/model${MODELNUM}"
			echo "ENDMDL"
		done
		
		echo "END"
	} \
	> "$OUTFILE"
fi

if [ -n "$SCORING_SET_FILE" ]
then
	cat "${TMPLDIR}/input" | xargs -L 1 basename | sed 's/[^0-9]\+/ /g' | awk '{print $NF}' > "${TMPLDIR}/selected_model_numbers"
	
	cat "$SCORING_SET_FILE" | egrep '^REMARK ' | egrep '^REMARK .* MODEL .* MD5 ' > "${TMPLDIR}/md5_codes"
	
	{
		if [ -n "$BRKFILE" ]
		then
			cat "$BRKFILE" | egrep '^HEADER|^COMPND'
		else
			cat "$SCORING_SET_FILE" | egrep '^HEADER|^COMPND'
		fi
				
		echo "AUTHOR    $AUTHORS"
		
		cat "${TMPLDIR}/selected_model_numbers" | while read MODELNUM
		do
			cat "${TMPLDIR}/md5_codes" | grep " ${MODELNUM} MD5 "
		done
		
		seq 1 "$NUMBER_OF_MODELS" \
		| while read MODELNUM
		do
			echo "   $MODELNUM" | sed 's/.*\(....\)$/MODEL \1/'
			cat "${TMPLDIR}/model${MODELNUM}"
			echo "ENDMDL"
		done
		
		echo "END"
	} \
	> "$OUTFILE"
fi

cat "${TMPLDIR}/input"

